default: all

# What to build

FILES := \
preprocessor.v \

#preprocessor_ep3.v \

# Build options

VP3_OPTS := -y .

# What to compile

TOP := \
preprocessor.v \

#preprocessor_ep3.v \

# Build exceptions

#VP3_OPTS.preprocessor_ep3 := -p ep3

#preprocessor_ep3.vp : preprocessor.vp
#	@cp $< $@

# Dependencies

# Rules

include ../rules.make
