// Generated by vp3

// This test checks our behavior when a -y library file that we know how to
// find (chameleon_mods) defines another module that we can't find based on
// the -y mechanism.
//
// Makefile runs two variants, one with the -v needed to find
// chameleon_other_mod, and one without.

//|@Module -v2k;
module chameleon2 (
      input wire  ai
    , output wire  ao
    , input wire  bi
    , output wire  bo
);

//|@Instance chameleon_mods ua -connect /^/ a;
chameleon_mods ua (
 .i(ai)
,.o(ao)
);

//|@Instance chameleon_other_mod ub -connect /^/ b;
chameleon_other_mod ub (
 .i(bi)
,.o(bo)
);

endmodule
