// Generated by vp3

module basic ();

//|@Wires;
wire  scalar_i;
wire  scalar_o;
wire [15:0] vector_i;
wire [15:0] vector_o;

//|@Instance submod s;
submod s (
 .scalar_i(scalar_i)
,.scalar_o(scalar_o)
,.vector_i(vector_i[15:0])
,.vector_o(vector_o[15:0])
);

//|@Waive no_source vector_i;
//|@Waive no_source scalar_i;

//|@Waive no_sink vector_o;
//|@Waive no_sink scalar_o;

endmodule
