// Generated by vp3

//|@Module -v2k;
module connect (
      output wire  s1_scalar
    , output wire [15:0] s1_vector
    , input wire  scalar_i
    , output wire  scalar_o
    , input wire [15:0] vec_s0_i
    , output wire [15:0] vec_s0_o
    , input wire [15:0] vector_i
);

//|@Wires;

//|@Instance submod s0
//|    -connect /^vector_/ vec_s0_
//|;
submod s0 (
 .scalar_i(scalar_i)
,.scalar_o(scalar_o)
,.vector_i(vec_s0_i[15:0])
,.vector_o(vec_s0_o[15:0])
);

//

//|@Instance submod s1
//|    -connect (.*)_o s1_${1}
//|;
submod s1 (
 .scalar_i(scalar_i)
,.scalar_o(s1_scalar)
,.vector_i(vector_i[15:0])
,.vector_o(s1_vector[15:0])
);

endmodule
