// Generated by vp3

//|@Module -v2k;
module ranges (
      input wire  s0_scalar_i
    , output wire  s0_scalar_o
    , output wire [16:0] s1_hiconn_toobig_explicit
    , input wire [16:0] s1_hiconn_toobig_implicit
    , input wire  s1_scalar_i
    , output wire  s1_scalar_o
    , output wire [14:0] s2_hiconn_toosmall_explicit
    , input wire [15:0] s2_hiconn_toosmall_implicit
    , input wire  s2_scalar_i
    , output wire  s2_scalar_o
);

//|@Wires;
wire [31:0] s0_hiconn_slice;

//|@Instance submod s0
//|    -connect vector_i s0_hiconn_slice[31:16]
//|    -connect vector_o s0_hiconn_slice[15:0]
//|    -connect scalar_i s0_scalar_i
//|    -connect scalar_o s0_scalar_o
//|;
submod s0 (
 .scalar_i(s0_scalar_i)
,.scalar_o(s0_scalar_o)
,.vector_i(s0_hiconn_slice[31:16])
,.vector_o(s0_hiconn_slice[15:0])
);

//

//|@Vector 17 s1_hiconn_toobig_implicit;

//|@Instance submod s1
//|    // no warning, but maybe should be
//|    -connect vector_i s1_hiconn_toobig_implicit
//|    // warning
//|    -connect vector_o s1_hiconn_toobig_explicit[16:0]
//|    -connect scalar_i s1_scalar_i
//|    -connect scalar_o s1_scalar_o
//|;
submod s1 (
 .scalar_i(s1_scalar_i)
,.scalar_o(s1_scalar_o)
,.vector_i(s1_hiconn_toobig_implicit[15:0])
,.vector_o(s1_hiconn_toobig_explicit[16:0])
);

//

//|@Vector 15 s2_hiconn_toosmall_implicit;

//|@Instance submod s2
//|    // no warning, but maybe should be
//|    -connect vector_i s2_hiconn_toosmall_implicit
//|    // warning
//|    -connect vector_o s2_hiconn_toosmall_explicit[14:0]
//|    -connect scalar_i s2_scalar_i
//|    -connect scalar_o s2_scalar_o
//|;
submod s2 (
 .scalar_i(s2_scalar_i)
,.scalar_o(s2_scalar_o)
,.vector_i(s2_hiconn_toosmall_implicit[15:0])
,.vector_o(s2_hiconn_toosmall_explicit[14:0])
);

endmodule
