// Generated by vp3

//|@Module -v2k;
module submod (
      input wire  scalar_i
    , output wire  scalar_o
    , input wire [15:0] vector_i
    , output wire [15:0] vector_o
);

//|@Vector 16 vector_i;
//|@Vector 16 vector_o;

assign vector_o = vector_i;

assign scalar_o = scalar_i;

endmodule
