// Generated by vp3

`include "test.vh"

//|@Module ;
module defines (
      YES
    , bugaboo_defined
    , bugaboo_undef2
    , synthesis_defined
    , x22
);

//|@Ports ;
output  YES;
output  bugaboo_defined;
output  bugaboo_undef2;
output  synthesis_defined;
output  x22;

//|@Regs ;

// FOO is defined in test.vh
assign `FOO = 1'b1;

`ifdef SYNTHESIS
    assign synthesis_defined = 1'b1;
    assign `SYNTHESIS = 1'b1;
`else
    assign synthesis_undef = 1'b1;
`endif

`ifndef BUGABOO
    assign bugaboo_undef = 1'b1;
`else
    assign bugaboo_defined = 1'b1;
`endif

`undef BUGABOO

`ifndef BUGABOO
    assign bugaboo_undef2 = 1'b1;
`else
    assign bugaboo_defined2 = 1'b1;
`endif

endmodule
