// Generated by vp3

//|@Module -none;

//|@Regs;
reg  test_reg;
//|@Wires;
wire [1:0] iport;
wire [1:0] oport;

//|@Instance syntax_sub u;
syntax_sub u (
 .oport(oport[1:0])
,.iport(iport[1:0])
);

initial test_reg = 0;
