// Generated by vp3

//|@Module sub1;
module sub1 (
      i1
    , o1
);

//|@Ports;
input  i1;
output  o1;

assign o1 = i1;

endmodule


//|@Module top;
module top (
      i1
    , i2
    , o1
    , o2
);

//|@Ports;
input  i1;
input  i2;
output  o1;
output  o2;
//|@Wires;
wire  i1;
wire  i2;
wire  o1;
wire  o2;

//|@Instance sub1 sub10;
sub1 sub10 (
 .i1(i1)
,.o1(o1)
);

//|@Instance sub2 sub20;
sub2 sub20 (
 .i2(i2)
,.o2(o2)
);

endmodule


//|@Module sub2;
module sub2 (
      i2
    , o2
);

//|@Ports;
input  i2;
output  o2;

assign o2 = i2;

endmodule
