// Generated by vp3

//|@Module noports1;
module noports1 (
      a
    , b
);

input a;
output b;

//|@Regs ;
//|@Wires ;
wire  c;
wire  d;

assign b = a;
assign d = c;

endmodule

//|@Module -v2k noports2;
module noports2 (
      input wire  a
    , output wire  b
    , input wire  c
    , output wire  d
);

//|@Regs ;
//|@Wires ;

assign b = a;
assign d = c;

endmodule

module noports3;

endmodule
