// Generated by vp3

//|@Module ;
module search (
      misnamed_i
    , misnamed_o
);

//|@Ports ;
input  misnamed_i;
output  misnamed_o;

//|@Instance -file wrongname.v misnamed m ;
misnamed m (
 .misnamed_i(misnamed_i)
,.misnamed_o(misnamed_o)
);

endmodule
