// Generated by vp3

//|@Module ;
module unparsed (
      clk
    , d
    , q
);

//|@Ports ;
input  clk;
input  d;
output  q;
//|@Wires ;
wire  clk;
wire  d;

always @(posedge clk) q <= d;

// These would be syntax errors

//|@Unparsed begin;
    w1 = w0;
//|@Unparsed end;

  //|@Unparsed begin;
    w3 = w2;
  //|@Unparsed end;

//|@Unparsed begin;
    w5 = w4;
  //|@Unparsed end;

  //|@Unparsed begin;
    w7 = w6;
//|@Unparsed end;

endmodule
