// Generated by vp3

module subA (
    input wire i
  , output wire o
);

    assign o = i;

endmodule

module subB (
    input wire i
  , output reg o
);

    always @(*) o = i;

endmodule

module subC (
    input wire i
  , output wire o1, o2
);

    assign o1 = i;
    assign o2 = i;

endmodule

module subD (
    input wire i
  , output reg o1, o2
);

    always @(*) begin
        o1 = i;
        o2 = i;
    end

endmodule

module top ();

    //|@Instance subA subA -connect (.*) a_$1;
    subA subA (
     .i(a_i)
    ,.o(a_o)
    );

    //|@Instance subB subB -connect (.*) b_$1;
    subB subB (
     .i(b_i)
    ,.o(b_o)
    );

    //|@Instance subC subC -connect (.*) c_$1;
    subC subC (
     .i(c_i)
    ,.o1(c_o1)
    ,.o2(c_o2)
    );

    //|@Instance subD subD -connect (.*) d_$1;
    subD subD (
     .i(d_i)
    ,.o1(d_o1)
    ,.o2(d_o2)
    );

endmodule
