// Generated by vp3



module test (a, b, c, d);

//|@Ports ;
input [15:0] a;
output  c;
output  d;
input  i;
output [22:0] o;

//|@Instance subA subA0 ;
subA subA0 (
 .i(i)
,.a(a[15:0])
,.b(b[15:0])
,.o(o)
);

//|@Instance subB subB0 ;
subB subB0 (
 .i(i)
,.o(o[22:0])
);

assign b = a;
assign c = a;
assign d = a;

endmodule
