default: all

# What to build

FILES := \
attr.v \

# Build options

VP3_OPTS := -y .

TOP := \

# Not included in TOP:
# attr.v: iverilog doesn't support all attribute types

# Build exceptions

# Dependencies

# Rules

include ../rules.make
