// Generated by vp3

// This covers the attribute uses that I expect are most common, but there are
// others

//|@Module -v2k -attr "mod_attr=\"mod_value\"";
(* mod_attr="mod_value" *) module attr (
      input wire  clk
    , input wire  in
    , output wire  subout0_subin1
);

(* reg_attr="reg_value" *) reg q;

always @(posedge clk)
    (* stmt_attr="stmt_value" *) q <= in;

assign subin0 = g (f (q));

// TODO: port connection attributes
// (* named_port_conn_attr="named_value" *)
(* inst_attr="inst_value" *) sub sub0 (.subin(subin0), .subout(subout0_subin1));

//sub sub1 (subout0_subin1, (* ordered_port_conn_attr="ord_value" *) subout1);

function f;
(* tf_input_attr="tf_input_value" *) input i;
f = i;
endfunction

function g ((* tf_v2k_input_attr="tf_v2k_input_value" *) input i);
g = i;
endfunction

endmodule

(* mod_attr="mod_value" *) module sub (
    subin,
    subout
);

(* port_attr="port_value" *) input subin;
output subout;

(* mod_item_attr="mod_item_value" *) assign subout = subin;

endmodule

//|@Module -v2k -attr "_23456_10_123456_20_123456_30_123456_40_123456_50_123456_60_1" long_attr;
(* _23456_10_123456_20_123456_30_123456_40_123456_50_123456_60_1 *)
module long_attr (
);

endmodule

// vim: sts=4 sw=4 et
