// Generated by vp3





// Should not be expanded: MACRO1

/* Should not be expanded:
 * MACRO2
 */

/* Should not be evaluated:

   @perl_begin
       vprint "test\n";
   @perl_end
 */

//|@Module;
module preprocessor (
      a
    , b
    , q
    , s
);

//|@Ports;
input  a;
input  b;
output  q;
input  s;

assign q = s ? b : a;

endmodule
