// Generated by vp3




// Should not be expanded: MACRO1

/* Should not be expanded:
 * MACRO2
 */

/* Should not be evaluated:

   @perl_begin
       vprint "test\n";
   @perl_end
 */

//|@Module;
module preprocessor (
      a
    , b
    , m1val
    , m2val
    , q
    , s
);

//|@Ports;
input  a;
input  b;
output  m1val;
input  m2val;
output  q;
input  s;

assign q = s ? b : a;

  assign m1val = m2val;

endmodule
